apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["touch", "/data/111"]
        volumeMounts:
        - mountPath: /data
          name: data
          subPath: app1
      restartPolicy: Never
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: 'my-pvc'
  backoffLimit: 0
